// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.example.rapid.domain;

import com.example.rapid.domain.WorkEntry;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect WorkEntry_Roo_Configurable {
    
    declare @type: WorkEntry: @Configurable;
    
}
